function [ speaker_samples ] = audiopartition( audio_samples, number_of_speakers )
%AUDIOPARTITION Randomly assign audio samples to speakers
%   If the sound described by audio_samples is intended to be generated by
%   number_of_speakers speakers, this function produces a random assignment
%   of the samples in audio_samples to speakers.
%
%audio_samples should be nx1
%number_of_speakers is an integer
%speaker_samples is nxnumber_of_speakers

number_of_samples=length(audio_samples);
speaker_samples=zeros(number_of_samples,number_of_speakers);
assignment=randi(number_of_speakers,number_of_samples,1);

for speaker = 1:number_of_speakers
    speaker_samples(1:end,speaker)=audio_samples .* (assignment==speaker);
end %for speaker

return

end

