function [ listener_samples ] = superimposeatposition( speaker_samples, speaker_positions, listener_position, sound_speed )
%SUPERIMPOSEATPOSITION Determine the sound that a user will hear
%   Assuming that that each column in speaker_samples is a time-record of
%   audio samples being generated by a different speaker (with three-space coordinates given in meters by speaker_positions),
%   superimposeatposition returns samples from the sound waveform perceived
%   by a listener at the three-space position listener_position (in
%   meters).
%   
%speaker_samples is nxm
%speaker_positions is 3xm
%listener_position is 3x1
%sound_speed is the speed of sound in m/s
%listener_samples is nx1

number_of_speakers=size(speaker_samples,2);
tdoa=zeros(1,m);
baseline_tdoa=pythag(speaker_positions(1:end,1),listener_position)/sound_speed;

for speaker=2:number_of_speakers
    tdoa(1,speaker)=pythag(speaker_positions(1:end,speaker),listener_position)/sound_speed-baseline_tdoa;
end %for speaker

function [ dist ] = pythag(x0,x1)
dx=x0-x1;
dist = sqrt((dx(1)).^2 + (dx(2)).^2 + (dx(3)).^2);
return
end